[package]
name = "wc-web-renderer"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wallpaper-console-web-renderer"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
gtk = "0.18.2"
gtk-layer-shell = { version = "0.8.2", features = ["v0_6"] }
webkit2gtk = { version = "2.0.2", features = ["v2_30"] }

[dev-dependencies]
tempfile.workspace = true
