// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bridge exposes Wails-bound methods to the React frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Apply(path: string): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.Apply", path);
}

/**
 * Binary returns the path to the Rust CLI (for logging / diagnostics).
 */
export function Binary(): $CancellablePromise<string> {
    return $Call.ByName("main.Bridge.Binary");
}

/**
 * BrowseDirectory opens a native directory picker.
 * Tries Wails v3 dialog API first, falls back to zenity/kdialog.
 */
export function BrowseDirectory(): $CancellablePromise<string> {
    return $Call.ByName("main.Bridge.BrowseDirectory");
}

export function ConfigGet(key: string): $CancellablePromise<string> {
    return $Call.ByName("main.Bridge.ConfigGet", key);
}

export function ConfigSet(key: string, value: string): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.ConfigSet", key, value);
}

export function FavoriteAdd(path: string): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.FavoriteAdd", path);
}

export function FavoriteRemove(path: string): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.FavoriteRemove", path);
}

export function FavoritesList(): $CancellablePromise<string[] | null> {
    return $Call.ByName("main.Bridge.FavoritesList");
}

export function HistoryClear(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.HistoryClear");
}

export function HistoryList(): $CancellablePromise<$models.HistoryDTO[] | null> {
    return $Call.ByName("main.Bridge.HistoryList");
}

export function LibraryCount(): $CancellablePromise<$models.LibraryCountDTO | null> {
    return $Call.ByName("main.Bridge.LibraryCount");
}

export function LibraryList(source: string): $CancellablePromise<$models.WallpaperDTO[] | null> {
    return $Call.ByName("main.Bridge.LibraryList", source);
}

export function LibraryPage(source: string, filter: string, sort: string, search: string, offset: number, limit: number): $CancellablePromise<$models.LibraryPageDTO | null> {
    return $Call.ByName("main.Bridge.LibraryPage", source, filter, sort, search, offset, limit);
}

export function MigrateToSqlite(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.MigrateToSqlite");
}

export function OpenPath(path: string): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.OpenPath", path);
}

export function RemoveMissingSources(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.RemoveMissingSources");
}

export function Rescan(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.Rescan");
}

export function Restore(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.Restore");
}

export function RevealInFileManager(path: string): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.RevealInFileManager", path);
}

export function ScanSteamWorkshop(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.ScanSteamWorkshop");
}

export function SourceAdd(path: string): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.SourceAdd", path);
}

export function SourceRemove(path: string): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.SourceRemove", path);
}

export function SourcesList(): $CancellablePromise<$models.SourceDTO[] | null> {
    return $Call.ByName("main.Bridge.SourcesList");
}

export function SqliteBackup(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.SqliteBackup");
}

export function SqliteExportFlat(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.SqliteExportFlat");
}

export function SqliteRestore(path: string): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.SqliteRestore", path);
}

export function SqliteResync(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.SqliteResync");
}

export function SqliteVerify(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.SqliteVerify");
}

export function Status(): $CancellablePromise<$models.StatusDTO | null> {
    return $Call.ByName("main.Bridge.Status");
}

export function Stop(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.Stop");
}

export function ThumbnailCacheClear(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.ThumbnailCacheClear");
}

export function ThumbnailCacheStatus(): $CancellablePromise<$models.ThumbnailCacheDTO | null> {
    return $Call.ByName("main.Bridge.ThumbnailCacheStatus");
}

export function ThumbnailFor(path: string): $CancellablePromise<$models.ThumbnailDTO | null> {
    return $Call.ByName("main.Bridge.ThumbnailFor", path);
}

export function ValidateSources(): $CancellablePromise<$models.CommandResult> {
    return $Call.ByName("main.Bridge.ValidateSources");
}
