// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CommandResult {
    "success": boolean;
    "stdout": string;
    "stderr": string;
    "exitCode": number;
}

export interface HistoryDTO {
    "path": string;
}

export interface LibraryCountDTO {
    "total": number;
    "images": number;
    "gifs": number;
    "videos": number;
}

export interface LibraryPageDTO {
    "total": number;
    "items": WallpaperDTO[] | null;
}

export interface SourceDTO {
    "path": string;
    "exists": boolean;
    "isWE": boolean;
    "label": string;
}

export interface StatusDTO {
    "configDir": string;
    "current": string;
    "lastBackend": string;
    "sourceCount": number;
}

export interface ThumbnailCacheDTO {
    "dir": string;
    "size": string;
    "entries": number;
}

export interface ThumbnailDTO {
    "path": string;
    "thumbnail"?: string;
    "cacheHit": boolean;
}

export interface WallpaperDTO {
    "path": string;
    "type": string;
    "ext": string;
    "backend": string;
    "size": number;
    "mtime": number;
    "resolution": string;
}
